name: GrapesRPG
main: me.trqhxrd.grapesrpg.Grapes
version: ${project.version}
api-version: 1.16
commands:
  grapes:
    description: GrapesRPG Main-Command.
    usage: Do /grapes help for more info.
  color:
    description: Gives you a random color.
    usage: /color