name: GrapesRPG
main: me.trqhxrd.grapesrpg.Grapes
version: ${project.version}
api-version: 1.16
commands:
  grapes:
    description: GrapesRPG Main-Command.
    usage: Do /grapes help for more info.
  color:
    description: Gives you a random color.
    usage: /color
  skill:
    description: Shows you your skill data.
    usage: /skill help for more information.
  pay:
    description: You can pay another player ingame cash using this command.
    usage: /pay <player> <amount>
  balance:
    description: This command gives you all the information about your or another players balance.
    usage: /balance [player]
    aliases:
      - bal
  economy:
    description: This command is used for administrating the economy on the server.
    usage: Do /economy help for more information
    aliases:
      - eco
