name: GrapesRPG
main: me.trqhxrd.grapesrpg.Grapes
version: ${project.version}
api-version: 1.16
commands:
  grapes:
    description: GrapesRPG Main-Command.
    usage: Do /grapes help for more info.
  color:
    description: Gives you a random color.
    usage: /color
  material:
    description: gives you the material of the item in your hand.
    usage: /material
  npc:
    description: Command for managing NPCs.
    usage: /npc help for more information.
  skill:
    description: Shows you your skill data.
    usage: /skill help for more information.